/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { HelicopterModel } from '../types/game';

export const HELICOPTER_FLEET: HelicopterModel[] = [
  {
    id: 'schweizer-300',
    name: 'Schweizer S-300 Light Trainer',
    callsign: 'RESCUE-01',
    description: 'Lightweight, ultra-agile training helicopter. Low operating cost, excellent low-speed hover stability for beginner rescue pilots.',
    price: 0,
    unlocked: true,
    maxSpeed: 85,
    climbRate: 850,
    maxAltitude: 700,
    fuelCapacity: 50,
    waterCapacity: 120,
    passengerCapacity: 2,
    agility: 1.25,
    durability: 70,
    color: '#eab308', // Amber yellow
    rotorBladeCount: 3,
    hasWaterCannon: true,
    hasSearchlight: true,
    hasMegaphone: true,
    winchSpeed: 25,
  },
  {
    id: 'bell-206',
    name: 'Bell 206L JetRanger',
    callsign: 'SKYWATCH-4',
    description: 'The classic municipal workhorse. Exceptional turbine reliability, balanced passenger capacity, and rapid dispatch speed.',
    price: 15000,
    unlocked: false,
    maxSpeed: 115,
    climbRate: 1100,
    maxAltitude: 900,
    fuelCapacity: 110,
    waterCapacity: 260,
    passengerCapacity: 4,
    agility: 1.0,
    durability: 100,
    color: '#0284c7', // Sky blue & white
    rotorBladeCount: 2,
    hasWaterCannon: true,
    hasSearchlight: true,
    hasMegaphone: true,
    winchSpeed: 35,
  },
  {
    id: 'md-500',
    name: 'MD-500E Defender SWAT',
    callsign: 'AIR-TAC-9',
    description: 'Distinctive egg-shaped airframe with a five-blade rotor system. Unrivaled responsiveness, ideal for tactical suspect tracking and tight rooftop extractions.',
    price: 32000,
    unlocked: false,
    maxSpeed: 135,
    climbRate: 1400,
    maxAltitude: 1000,
    fuelCapacity: 130,
    waterCapacity: 320,
    passengerCapacity: 4,
    agility: 1.45,
    durability: 110,
    color: '#334155', // Slate tactical dark
    rotorBladeCount: 5,
    hasWaterCannon: true,
    hasSearchlight: true,
    hasMegaphone: true,
    winchSpeed: 40,
  },
  {
    id: 'as365-dauphin',
    name: 'Eurocopter AS365 Dauphin',
    callsign: 'MEDEVAC-1',
    description: 'Twin-turbine all-weather search & rescue flagship with fenestron enclosed tail rotor. High payload capacity for intensive trauma transport.',
    price: 58000,
    unlocked: false,
    maxSpeed: 150,
    climbRate: 1650,
    maxAltitude: 1200,
    fuelCapacity: 220,
    waterCapacity: 500,
    passengerCapacity: 6,
    agility: 0.95,
    durability: 140,
    color: '#ef4444', // Coast Guard Red / White
    rotorBladeCount: 4,
    hasWaterCannon: true,
    hasSearchlight: true,
    hasMegaphone: true,
    winchSpeed: 50,
  },
  {
    id: 'skycrane-ch54',
    name: 'Sikorsky S-64 Skycrane',
    callsign: 'FIRE-BOMB-88',
    description: 'Colossal heavy-lift aerial firefighting colossus. Carries an immense 800-gallon belly tank capable of dousing entire high-rise infernos in a single pass.',
    price: 110000,
    unlocked: false,
    maxSpeed: 105,
    climbRate: 950,
    maxAltitude: 850,
    fuelCapacity: 350,
    waterCapacity: 800,
    passengerCapacity: 8,
    agility: 0.65,
    durability: 200,
    color: '#ea580c', // Fire Rescue Hi-Vis Orange
    rotorBladeCount: 6,
    hasWaterCannon: true,
    hasSearchlight: true,
    hasMegaphone: true,
    winchSpeed: 30,
  },
];
